config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :event_attendings, only: [:create, :destroy]
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root to: "events#index"
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :organizer, class_name: "User"
    has_many :event_attendings, foreign_key: :attended_event_id
    has_many :attendees, through: :event_attendings, source: :attendee
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all.order("created_at DESC")
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @user = User.all
    @event = Event.find(params[:id])
    if @event.nil?
      render action: "index"
    end
  end

  # GET /events/new
  def new
    @event = current_user.organized_events.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.organized_events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to root_path, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to root_path, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:event_name, :event_date, :event_location)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_attendance.html.erb
    <div class="container">
      <h1 class="title is-4">Attendees</h1>
      <% event.attendees.each do |attendee| %>
        <div class="content">
          <div class="columns">
            <div class="column">
              <p> <%= attendee.name %> </p>
            </div>

            <% if user_signed_in? && current_user.id == event.organizer_id%>  
              <div class="column">
                <%= link_to 'Delete', event_event_attending_path(event, :user_id => attendee.id),
                method: :delete, class: "button is-small" %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

app/views/events/_form.html.erb
<div class="columns is-centered">
  <div class="column is-4">
    <div class="box">
      <%= form_with(model: event, local: true) do |f| %>
        <% if event.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

            <ul>
            <% event.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= f.label :event_name %><br />
          <%= f.text_field :event_name, class: "input", placeholder: "Late night karaoke" %>
        </div>
        <div class="field">
          <%= f.label :event_date %><br />
          <%= f.date_field :event_date, class: "input", placeholder: "10-07-2020" %>
        </div>
        <div class="field">
          <%= f.label :event_location %><br />
          <%= f.text_field :event_location, class: "input", placeholder: "Singapore" %>
        </div>

        <br />

        <div class="actions center-line-text">
          <%= f.submit "Create Event", class:"button is-light" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/_info.html.erb
<div class="center-line-text">
  <p class="title is-6"><%= event.event_name %> </p>
  <p>Location : <%= event.event_location %> </p>
  <p>Date     : <%= event.event_date %> </p>
  <p>
    Organized by <strong>
      <% if user_signed_in? &&  event.organizer.name == current_user.name %>
          You
      <% else %>
        <%= event.organizer.name %> 
      <% end %>
    </strong>
  </p> 
</div>

app/views/events/_invite.html.erb
    <div class="container">
      <h1 class="title is-4 center-line-text">Invite</h1>
      <% user.each do |attendee| %>
        <% if event.organizer_id != attendee.id && !event.attendees.exists?(:id => attendee.id)%>
          <div class="content">
            <div class="columns is-centered">
              <div class="column is-half">
                <p> <%= attendee.name %> </p> 
              </div>
            
            <div class="column">
              <%= form_with(model: event, url: event_event_attendings_path(event), method: "post") do |form| %>
                <%= hidden_field_tag(:user_id, attendee.id) %>
                <%= hidden_field_tag(:event_id, event.id) %>
                <%= form.submit "invite", class: "button is-small"%>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>

app/views/events/edit.html.erb
<h1 class="center-line-text title">Editing Event</h1>
<div class="hero is-fullheight">
  <%= render 'form', event: @event %>
</div>

app/views/events/index.html.erb
  <div class="container is-fluid center-line-text">
    <p class="event title is-3">Events</p>
  </div>

  <div class="columns is-centered">
    <div class="column is-one-third">
      <hr>
      <% @events.each do |event| %>
        <%= link_to event_path(event) do %>
          <div class="box event-box">
            <div class="content">
              <%= render 'info', event: event %>
            </div>
          </div>

        <% end %>  
      <% end %>
    </div>

    <br />
  </div>

app/views/events/new.html.erb
<h1 class="center-line-text title">Create New Event</h1>

<div class="hero is-fullheight">
  <%= render 'form', event: @event %>
</div>

app/views/events/show.html.erb
<div class="hero is-fullheight">
  <div class="columns is-centered">

    <div class="column is-one-third">

      <div class="box center-line-text">
        <div class="content">
          <%= render 'info', event: @event %>
        </div>

        <div class="content">
          <% if user_signed_in? && current_user.id == @event.organizer_id %> 
            <%= link_to 'Edit', edit_event_path(@event), class: "button is-small" %>
            <%= link_to 'Delete', @event, method: :delete, class: "button is-small",
              data: { confirm: 'Are you sure?' } %>
          <% end %> 
        </div>
      </div>
        
      <div class="box center-line-text">
        <%= render 'attendance', event: @event, user: @user %>
      </div>

      <% if user_signed_in? && current_user.id == @event.organizer_id%>
      <div class="box center-line-text">
        <%= render 'invite', event: @event, user: @user %>
      </div>
      
      <% else %>
        <div class="container center-line-text">
          <% if user_signed_in? && current_user.id != @event.organizer_id%>
            <%= form_with(model: @event, url: event_event_attendings_path(@event), method: "post") do |form| %>
              <%= hidden_field_tag(:user_id, current_user.id) %>
              <%= hidden_field_tag(:event_id, @event.id) %>
              <%= form.submit "Join Event!", class: "button is-small is-info"%>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>

  </div>
</div>