config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :event_attendings, only: [:create, :destroy]
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root to: "events#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Event Master</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container is-fluid">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>

    <nav class="navbar is-light">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-4">Event Master</h1>
        <% end %>
        <div class="navbar-burger burger" onclick="document.querySelector('.navbar-menu').classList.toggle('is-active');">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>
      <div class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
              <% if user_signed_in? %>
                <p class="control">
                  <%= link_to 'Create Event', new_event_path, class: "button is-light is-inverted" %>
                </p>
                <p>
                  <%= link_to "#{current_user.name} | Logout", destroy_user_session_path, method: :delete, class:"button is-light" %>
                </p>
              <% else %>
                <p>
                  <%= link_to 'Sign In', new_user_session_path, class: "button is-light" %>
                </p>
                <p>
                  <%= link_to 'Sign Up', new_user_registration_path, class: "button is-light" %>
                </p>
              <% end %>  
            </div>
          </div>
        </div>
      </div>
    </nav>

    <div class="container body-content">
      <%= yield %>
    </div>

  </body>
</html>